
#MySQL properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_microservices
    username: root
    password: Srilaxmi@9
    type: com.mchange.v2.c3p0.ComboPooledDataSource